# This is a complete example of a config.toml file for Porla.

db = ":memory:"
log_level = "info"

listen_interfaces = [
    ["0.0.0.0", 6881]
]

[http]
auth_token = "<random string>"
host = "127.0.0.1"
port = 1337

[presets.default]
max_uploads = 1000
storage_mode = "allocate"

[presets.my-preset-1]
max_uploads = 10

[session_settings]
base = "min_memory_usage"

[timer]
dht_stats = 5000
session_stats = 5000
torrent_updates = 1000

[[webhooks]]
on = "torrent_added"
url = "https://google.com"
