name: Beta

on:
  push:
    branches:
      - ccache

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.15
        with:
          versionSpec: '5.x'

      - name: Calculate version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.15
        with:
          useConfigFile: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          build-args: GITVERSION_SEMVER=${{ steps.gitversion.outputs.fullSemVer }}
          context: .
          load: true
          tags: porla

      - name: Copy Porla binary from image
        run: |
          docker create --name tmp porla
          docker cp tmp:/usr/bin/porla /tmp/porla
          docker rm -f tmp

      - name: Upload Porla binary to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: porla-linux-amd64
          path: /tmp/porla
